/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_hellojni_MainActivity */

#ifndef _Included_com_lenovo_hello2_MainActivity
#define _Included_com_lenovo_hello2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_hellojni_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lenovo_hello2_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
